# Generated by Django 6.0.3 on 2026-05-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_remove_jobalert_parentprofile_savedjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='note',
            field=models.CharField(blank=True, help_text='Optional 1–2 sentence intro — kept short on purpose.', max_length=400, verbose_name='Personal Note'),
        ),
    ]
