# Generated by Django 6.0.3 on 2026-05-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_digestlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ai_suggestion',
            field=models.CharField(blank=True, choices=[('shortlist', 'Shortlist'), ('hold', 'Hold'), ('decline', 'Decline')], max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='ai_summary',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
