# Generated by Django 6.0.3 on 2026-05-15 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_application_ai_suggestion_application_ai_summary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_resume_text', models.TextField(blank=True)),
                ('years_experience', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('top_skills', models.CharField(blank=True, help_text='Comma-separated, max 6.', max_length=400)),
                ('location_hint', models.CharField(blank=True, max_length=120)),
                ('schedule_preference', models.CharField(blank=True, help_text='Free-text hint: "mornings", "term-time", etc.', max_length=120)),
                ('summary', models.CharField(blank=True, help_text='1–2 sentence parent-friendly bio.', max_length=400)),
                ('parsed_at', models.DateTimeField(auto_now=True)),
                ('parse_failed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
