# Generated by Django 6.0.3 on 2026-05-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_parentprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.CharField(blank=True, help_text='e.g. "$15/hr", "€18/hr", "₹30,000/month". Leave blank if negotiable.', max_length=100, verbose_name='Pay Rate'),
        ),
    ]
